-- MySQL Script generated by MySQL Workbench
-- 05/16/14 10:22:29
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pinball
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `pinball` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
-- USE `pinball` ;

-- -----------------------------------------------------
-- Table `pinball`.`productes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u555588791_pinba`.`productes` ;

CREATE TABLE IF NOT EXISTS `u555588791_pinba`.`productes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` MEDIUMTEXT NOT NULL,
  `preu` FLOAT NOT NULL,
  `foto` VARCHAR(45) NOT NULL,
  `data_alta` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `u555588791_pinba`.`productes`
-- -----------------------------------------------------
START TRANSACTION;
USE `u555588791_pinba`;
INSERT INTO `u555588791_pinba`.`productes` (`id`, `nom`, `descripcio`, `preu`, `foto`, `data_alta`) VALUES (NULL, 'BINGO ELECTRONICO', 'bingo descr.', 235, 'bingo.jpg', curdate());
INSERT INTO `u555588791_pinba`.`productes` (`id`, `nom`, `descripcio`, `preu`, `foto`, `data_alta`) VALUES (NULL, 'KIT DE DIANA ZONE DART', 'diana descr.', 235, 'diana.jpg', curdate());
INSERT INTO `u555588791_pinba`.`productes` (`id`, `nom`, `descripcio`, `preu`, `foto`, `data_alta`) VALUES (NULL, 'ROULETTE', 'Rouleta electrónica', 235, 'roulette.jpg', curdate());
INSERT INTO `u555588791_pinba`.`productes` (`id`, `nom`, `descripcio`, `preu`, `foto`, `data_alta`) VALUES (NULL, 'COMMA6-A', 'comm descr.', 235, 'comma6a.jpg', curdate());
INSERT INTO `u555588791_pinba`.`productes` (`id`, `nom`, `descripcio`, `preu`, `foto`, `data_alta`) VALUES (NULL, 'STANDARD GAMES', 'games descr.', 235, 'standar_games.jpg', curdate());

COMMIT;

